"""Supplementary Figure 21: Inference cost split by task.

Reviewer minor comment #4 asked for a like-for-like comparison of inference
wall-clock and peak GPU memory between Evo2HiC and prior Hi-C predictors.
The Evo2HiC pipeline addresses **two distinct prediction tasks** (sequence
-> HiC denovo prediction, and Hi-C super-resolution conditioned on DNA);
mixing comparators across them would be misleading. This figure therefore
lays out the comparison as two rows — one per task — each with its own set
of bars.

  Row a/b/c — Task A: Sequence -> Hi-C
      Evo2HiC seq2hic ckpt  (CDNA2d, 4 kb, 1 Mb window)
      Orca-1M               (the published 1 Mb single-chunk Orca encoder)

  Row d/e/f — Task B: Hi-C super-resolution
      Evo2HiC SR ckpt       (CDNA2d / method_name=CDNAUNET, 2 kb, 320 kb
                             window, CNN DNA encoder)
      HiCARN-2              (40 x 40 patch SR network, no DNA conditioning)

Measurement protocol
--------------------
- Hardware: single NVIDIA H100 PCIe, `cuda:1`.
- 10 forward-pass iterations after 3 warm-up iterations; median reported.
- Numerical precision: fp32 (each model's default).
- Raw numbers in `revision/Minor/timing_results.tsv`, generated by
  `revision/Minor/timing_benchmark.py`.

Outputs
-------
Figures/supplementary_21.pdf
"""
from __future__ import annotations
import sys
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from paths import (                                              # noqa: E402
    ensure_out_dir, TIMING_TSV as TSV,
)

from plot_settings import colors as candidate_colors  # noqa: E402

OUT_PDF = ensure_out_dir() / "supplementary_21.pdf"

plt.style.use("seaborn-v0_8-white")
plt.rcParams.update({"font.size": 8, "font.family": "Arial"})

TASK_ORDER = ["Task A: Seq2HiC", "Task B: HiC SR"]
TASK_MODEL_ORDER = {
    "Task A: Seq2HiC": ["Evo2HiC", "Orca-1M"],
    "Task B: HiC SR":  ["Evo2HiC", "HiCARN-2"],
}
# Output areas matched within each task by appropriate batch sizing in
# revision/Minor/timing_benchmark.py:
#   Task A — both models output 1 Mb x 1 Mb / forward (batch=1 each)
#   Task B — Evo2HiC SR outputs 320 x 320 kb² / forward (batch=1);
#            HiCARN-2 patches are 80 x 80 kb² so we run batch=16 to
#            match the same 320 x 320 kb² area in a single forward.
TIME_YLABEL = "Time per patch (ms)"
MEM_YLABEL = "Peak memory per patch (GiB)"
COLOR_MAP = {
    "Evo2HiC":  candidate_colors[0],  # #fb8072
    "Orca-1M":  candidate_colors[2],  # #80b1d3
    "HiCARN-2": candidate_colors[3],  # #8dd3c7
}
PANEL_LABELS = {
    "Task A: Seq2HiC": ("a", "b", "c"),
    "Task B: HiC SR":  ("d", "e", "f"),
}


def _panel_label(ax, label):
    ax.text(-0.2, 1.18, label, transform=ax.transAxes,
            fontsize=12, fontname="Arial", fontweight="bold",
            ha="left", va="top")


def _bars(ax, models, values, *, ylabel, colors):
    """Linear-scale bar plot. No error bars (forward-pass timing has
    sub-millisecond spread that looks like noise dots) and no value
    labels above the bars — the y axis encodes the unit directly."""
    x = np.arange(len(models))
    ax.bar(x, values, color=colors, width=0.55, edgecolor="none")
    ax.set_xticks(x)
    ax.set_xticklabels(models, rotation=0)
    ax.set_ylabel(ylabel)
    vmax = max(values)
    ax.set_ylim(0, vmax * 1.10)
    # Unified tick density across panels
    ax.yaxis.set_major_locator(MaxNLocator(nbins=5))
    ax.tick_params(axis="both", length=2)
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)
    for spine_name in ("left", "bottom"):
        ax.spines[spine_name].set_linewidth(0.5)


def main():
    df = pd.read_csv(TSV, sep="\t")
    if "task" not in df.columns:
        raise SystemExit(
            f"{TSV} is missing the 'task' column. Re-run "
            "revision/Minor/timing_benchmark.py to regenerate it."
        )
    print(df[["task", "model", "params", "time_median_s", "peak_mem_GiB"]].to_string(index=False))

    fig, axes = plt.subplots(2, 3, figsize=(7.5, 4.6), constrained_layout=True)

    for row, task in enumerate(TASK_ORDER):
        sub = df[df["task"] == task].copy()
        models_in_order = [m for m in TASK_MODEL_ORDER[task] if m in sub["model"].tolist()]
        sub = sub.set_index("model").loc[models_in_order]
        colors = [COLOR_MAP[m] for m in sub.index]
        labels = sub.index.tolist()
        a_lbl, b_lbl, c_lbl = PANEL_LABELS[task]

        # forward-pass time (ms) — linear scale, output area matched by
        # batch sizing in the benchmark runner.
        times_ms = sub["time_median_s"].to_numpy() * 1e3
        _bars(axes[row][0], labels, times_ms,
              ylabel=TIME_YLABEL, colors=colors)
        _panel_label(axes[row][0], a_lbl)

        # peak GPU memory (GiB)
        mem_gib = sub["peak_mem_GiB"].to_numpy()
        _bars(axes[row][1], labels, mem_gib,
              ylabel=MEM_YLABEL, colors=colors)
        _panel_label(axes[row][1], b_lbl)

        # parameter count (M)
        params_M = sub["params"].to_numpy() / 1e6
        _bars(axes[row][2], labels, params_M,
              ylabel="Parameters (M)", colors=colors)
        _panel_label(axes[row][2], c_lbl)

        # Task identification (Task A row a-c, Task B row d-f) is left to
        # the figure caption — keeping the figure free of in-axes titles
        # avoids collisions and clutter.

    fig.savefig(OUT_PDF, bbox_inches="tight")
    print(f"[wrote] {OUT_PDF}")


if __name__ == "__main__":
    main()
